language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
before_script:
  - sudo apt-get install libboost-test-dev -y
script:
  - cd ./01_hello
  - cmake -H. -Bcmake
  - cmake --build cmake
  - cmake --build cmake --target test
  - cmake --build cmake --target package
  - cd ../02_ip_filter
  - cmake -H. -Bcmake
  - cmake --build cmake
  - cmake --build cmake --target test
  - cmake --build cmake --target package
  - cd ../03_allocator
  - cmake -H. -Bcmake
  - cmake --build cmake
  - cmake --build cmake --target test
  - cmake --build cmake --target package
  - cd ..
deploy:
  skip_cleanup: true
  - provider: script
    script: curl -T ./01_hello/cmake/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uslonegd:$BINTRAY_API_KEY "https://api.bintray.com/content/slonegd/otus01/helloworld/0.0.$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: script
    script: curl -T ./02_ip_filter/cmake/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uslonegd:$BINTRAY_API_KEY "https://api.bintray.com/content/slonegd/otus01/ip_filter/0.0.$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: script
    script: curl -T ./03_allocator/cmake/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uslonegd:$BINTRAY_API_KEY "https://api.bintray.com/content/slonegd/otus01/allocator/0.0.$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"