language: cpp
before_script:
  - sudo apt-get install libboost-test-dev -y
script:
  - cd ./01_hello
  - cmake -H. -Bcmake
  - cmake --build cmake
  - cmake --build cmake --target test
  - cmake --build cmake --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ./01_hello/cmake/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uslonegd:$BINTRAY_API_KEY "https://api.bintray.com/content/slonegd/otus01/helloworld/0.0.$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
